# Generated by Django 4.2.11 on 2024-06-08 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_profile_posts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="post_titel",
            new_name="post_title",
        ),
    ]
