# Generated by Django 4.2.11 on 2024-06-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_rename_post_titel_posts_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="post_text",
            field=models.TextField(max_length=130),
        ),
    ]
