# Generated by Django 4.2.11 on 2024-06-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_posts_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="post_text",
            field=models.TextField(max_length=330),
        ),
    ]
